Lesson 8: Suggest appeal on session usage
mikairyuu/fefu_backend_2_3 pull request #7
Opened 2021-11-09 14:00 UTC by mikairyuu

Я не фронтендер, поэтому сделал самую базовую реализацию с алертом, надеюсь хватит...

2021-11-09 15:25 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +        if ($request->input('suggested') !== null)
А зачем редиректить? Чем это хуже, чем просто в шаблон прокинуть этот параметр из запроса?

2021-11-10 00:11 UTC, mikairyuu commented on app/Http/Middleware/SuggestionManager.php
> +    public function __construct(Setting $setting)
Как? Я наоборот на StackOF прочитал, что в handle нельзя dependency injection делать и нужно делать конструктор под это...

2021-11-10 00:41 UTC, mikairyuu commented on app/Http/Middleware/SuggestionManager.php
> +        if (session()->get('popup') === true || session()->get('appealed') === true)
Согласен, условие с popup здесь не нужно, я его использовал раньше, когда flash() вместо now() использовал.

2021-11-10 01:34 UTC, mikairyuu commented on app/Http/Controllers/AppealController.php
> +        if ($request->input('suggested') !== null)
Редиректить нужно, чтобы в query не осталось suggested=1, переданного из JS. Именно таким образом достигается исчезновение этой надписи при перезагрузке страницы. Если не убрать это редиректом, то бэкенд никак не поймёт, когда сообщение нужно убирать.

2021-11-10 02:14 UTC, mikairyuu commented on routes/web.php
> +Route::group(['middleware' => ['suggestions']], function () {
Окей, с этим есть... Миллион проблем. Начнём с того, что посредника я не могу сделать глобальным - в любом месте объявления его как глобального он перестаёт работать, как мне кажется, потому, что таким образом запускается раньше посредника StartSession в посредниках группы web. Впрочем, я могу объявить его в группе web, и это уже фактически работает как глобальный посредник, хоть формально им и не является. Далее - насчёт except. Свойства никакого нет. Все встроенные в ларавель посредники самостоятельно пробегают свой массив except и ищут там текущий роут. Так можно сделать, но это довольно громоздко. Свойство, про которое Вы сказали, это, вероятно, то, которое запускается через контроллер. Оно заставит меня прописывать это два раза в контроллере. Некрасиво. Я всё-таки считаю, что способ сделать группу самый компактный. Но, ради сохранения целей глобальности, пока оставлю реализацию, которую используют встроенные посредники.

2021-11-10 02:46 UTC, mikairyuu commented on resources/views/news.blade.php
> +        @if(session('popup')===true)
Читал, думал что и так пойдёт, потому что строго говоря ни один из этих подходов не сильно лучше, всё равно надо в каждый файл что-то вставлять. Сделал subview.

2021-11-11 14:57 UTC, chrn-feip commented on app/Http/Middleware/SuggestionManager.php
> +    public function __construct(Setting $setting)
Вы правы, в аргументы handle не получится подтянуть. Но можно обойтись без создания нового свойства в объекте посредника, тем более если оно нужно всего один раз в одном методе. Прямо внутри handle вызовите в переменную app(Settings::class)

2021-11-11 15:05 UTC, chrn-feip commented on routes/web.php
> +Route::group(['middleware' => ['suggestions']], function () {
Вы пробовали менять приоритет вызова посредника, управляя его порядком в $middlewareGroups['web']. Формально это посредник группы маршрутов, не глобальный, вы правы.

Для исключения можно смотреть на два способа:
1. https://laravel.com/docs/8.x/middleware#excluding-middleware
2. Пример работы с $except в родительском классе у посредника VerifyCsrfToken

В Нашем случае (т.е. посредник является "маршрутным", а не глобальным, как я изначально предполагала) достаточно варианта 1.

2021-11-11 15:56 UTC, chrn-feip requested changes

2021-11-11 15:56 UTC, chrn-feip commented on database/migrations/2021_11_08_042924_create_settings_table.php
> +        Schema::create('settings', function (Blueprint $table) {
Идентификатор тоже должен быть, несмотря на то, что в таблице пока что будет одна запись.

2021-11-11 16:04 UTC, chrn-feip commented on app/Http/Controllers/AppealController.php
> +        if ($request->input('suggested') !== null)
Редирект - это лишний запрос, перезагрузка страницы (хоть и быстрая, но заметная). Можно ввести ещё один параметр в сессии, который устанавливается после первого запроса с suggested и управляет каким-то флажком в шаблоне для показа сообщения. Если первый раз открыли с suggested, то показали, если нет - не показали. И сбросили этот параметр в случае, когда надо в очередной раз показать попап.

2021-11-12 02:42 UTC, merged