Lesson 9: Add posts and comments with API
mikairyuu/fefu_backend_2_3 pull request #8
Opened 2021-11-17 11:59 UTC by mikairyuu

2021-11-18 13:40 UTC, chrn-feip requested changes

2021-11-18 13:40 UTC, chrn-feip commented on database/seeders/DatabaseSeeder.php
> +            UserSeeder::class,
Повторный запуск сидера делали? Скорее всего упадёт из-за  truncate в каждом отдельном сидере и ограничения на внешний ключ. Нужно либо тут сделать предварительно удаление в обратной последовательности - от комментов к юзерам. Либо можете попробовать отключать проверку FK командами disableForeignKeyConstraints и enableForeignKeyConstraints (ищите их тут https://laravel.com/api/8.x).

2021-11-18 13:40 UTC, chrn-feip commented on app/Http/Controllers/PostController.php
> +        if ($validator->fails()) return response()->json($validator->errors()->first(), 400);
1. Почему только первая ошибка, а не все?
2. Для ответа с ошибками валидации лучше подходит статус 422

2021-11-18 13:40 UTC, chrn-feip commented on app/Http/Controllers/PostController.php
> +        return PostResource::collection(Post::with(['user', 'comments'])->ordered()->paginate(self::PAGE_SIZE));
Тут можно ещё сделать магию упорядочивания для комментариев:
для этого параметры with записываются как массив, в котором для ключа комментов значением является анонимная функция, внутри которой вызывается ordered скоуп уже комментариев.

Как в примере кода тут https://laravel.com/docs/8.x/eloquent-relationships#nested-eager-loading-morphto-relationships. Но только вам надо не MorphTo ожидать, а Builder (который Eloquent\Builder). Аргумент можно назвать $query.

2021-11-18 13:40 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        if ($post === null) return response()->json('Post not found!', 404);
Следите за структурой ответа, в других ответах же есть ключ message

2021-11-18 13:40 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
1. А разве Post не будет автоматически определён маршрутом по указанному там идентификатору в scoped?
2. Можно ещё потестировать случай, когда в урле слаг от одного поста, а id коммента от другого. Так вы поймёте, вычитывается ли пост при обработке маршрута и откуда вычитывается коммент - из отношения у загруженного поста или сам по себе из таблицы. Как только поймёте, так и решится вопрос нужности этой проверки или необходимости другой.

2021-11-18 13:40 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
То же самое про пост и возможную загрузку при маршрутизации

2021-11-18 13:40 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $comment = Comment::query()->whereBelongsTo($post)->paginate();
Лучше не так. Лучше у поста сделать with с ordered внутри на комментарии, если пост не вычитывается автоматически. Если вычитывается, то вызвать $post->comments()->ordered()->paginate(self::PAGE_SIZE).
Если пост загружается, то можно вообще сначала проверить, что отношение загружено (пока тестируете, чтобы понять, как писать дальше код). Если загружено, то написать доолинтельный метод ordered (уже без scope), который принимает коллекцию, а не конструктор запроса, и её упорядочивает аналогично. Поэкспериментируйте. Цель - минимизировать количество запросов в БД.

2021-11-18 13:40 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +    private const PAGE_SIZE = 5;
Не используете почему?

2021-11-19 00:43 UTC, mikairyuu commented on database/seeders/DatabaseSeeder.php
> +            UserSeeder::class,
Делал, не падает. Нужно что-то делать в таком случае?)

2021-11-19 00:58 UTC, mikairyuu commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
1. Именно так я и делал изначально, но потом обнаружил, к своему величайшему огорчению, что ларавель вызывает missing() замыкание только на последний аргумент урла, а не на все, что делает невозможным возвращать корректный JSON ответ в случае с отсутствующим постом.
2. Да, я дурачок, забыл этот функционал реализовать...

2021-11-19 01:18 UTC, chrn-feip commented on database/seeders/DatabaseSeeder.php
> +            UserSeeder::class,
Не нужно

2021-11-19 03:40 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
1. Тут речь не столько про missing, сколько про аргумент с типом Post в методе контроллера вместо $post_slug и необходимости выбирать $post ручками. Если при маршрутизации вложенного ресурса родительский тоже определяется, то почему бы это не использовать? В этом случае missing тоже только на комментарий сработает?

2021-11-19 08:24 UTC, mikairyuu commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
Именно про этот случай я и говорю, missing вызывается только при отсутвующем комментарии, при отсутвующем посте он выкидывал свой дефолтный 404, поэтому мне и пришлось делать это руками внутри контроллера...

2021-11-19 14:52 UTC, chrn-feip commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
Попробуйте ещё раз, missing срабатывает на оба параметра в урле: 
В методах контроллера комментариев должны быть аргументы Post $post (а не post_slug) и Comment $comment. В модели Post должно быть отношение comments, а в Comment - post. В scoped для маршрута комментариев должны быть указаны идентификаторы в обеих моделях. При невалидном посте или невалидной связи между постом и комментарием (коммент от другого поста) должна падать 404 ошибка из-за несуществующего комментария, это нормально.

2021-11-20 00:52 UTC, mikairyuu commented on app/Http/Controllers/CommentController.php
> +        $post = Post::query()->where('slug', $post_slug)->first();
Видимо я урл неправильно писал, реально работает же... Приношу свои извинения)

2021-11-25 02:52 UTC, chrn-feip requested changes

2021-11-25 02:52 UTC, chrn-feip commented on composer.json
> +        "spatie/laravel-collection-macros": "^7.8"
А это вам зачем понадобилось?

2021-11-25 03:45 UTC, mikairyuu commented on composer.json
> +        "spatie/laravel-collection-macros": "^7.8"
Чтоб коллекции paginate прописать...

2021-11-25 04:24 UTC, chrn-feip commented on composer.json
> +        "spatie/laravel-collection-macros": "^7.8"
Ладно, я поняла, откуда ноги растут. Ввела вас в заблуждение про загруженные комменты. Пагинация уже есть в конструкторе запросов, она встроена в ларавель. Поэтому излишне тащить целый новый пакет ради этой же фичи, из-за которой делается лишний запрос в БД. Лучше пожертвовать запросом. Т.е. в контроллере не запихивать в коллекцию уже загруженные маршрутом комменты, а сделать  $post->comments()->ordered()->paginate(self::PAGE_SIZE)

2021-11-25 09:22 UTC, mikairyuu commented on composer.json
> +        "spatie/laravel-collection-macros": "^7.8"
Ну так там под капотом и так встроенный используется, там макрос то на 5 строчек всего... Ладно, будь по вашему.

2021-11-25 11:05 UTC, chrn-feip commented on composer.json
> +        "spatie/laravel-collection-macros": "^7.8"
Лишние зависимости - это всегда выбор, очень тщательный. Макрос на 5 строчек можно и самим в коде написать, раз уж на то дело пошло. А вот пакет - это, условно "чёрный ящик", вы крайне редко или никогда будете заходить в папку с вендор кодом и интересоваться, а из чего состоит пакет, что он делает, кроме нужной одной функции в 5 строк, а точно ли там код написан оптимально и т.п.

2021-11-25 11:05 UTC, merged